### ISSUE TITLE
I dont know How to use it

### ISSUE THREAD

**Issue by Stark1937** [everettjf/moex#3]
brew install boost
qmake

I have install boost and qt, but I dont have 'qmake' in term ,how to use it...
Can you write it detailedly

**Comment by Naville** [comment]
Qt from Homebrew is broken it seems and lacks critical components.

Try Qt Offline installer for macOS, whch contains qmake

**Comment by Naville** [comment]
顺便maintainer都是中国人可以直接中文的哇

**Comment by everettjf** [comment]
都先别用啊。。。我还没搞完，只是不想花钱private repo了。。。。。
